// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgdvMj2O-eBYOvbjxC7YosuMVfXYf6vaY',
    appId: '1:994299555936:web:ead5e32b51642525bc1305',
    messagingSenderId: '994299555936',
    projectId: 'chat-app-f3159',
    authDomain: 'chat-app-f3159.firebaseapp.com',
    storageBucket: 'chat-app-f3159.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFq8BneGrFkC3Orivv0D_YAqDPPFOSXcs',
    appId: '1:994299555936:android:966be2d79f32c6a2bc1305',
    messagingSenderId: '994299555936',
    projectId: 'chat-app-f3159',
    storageBucket: 'chat-app-f3159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbgDC-7jRc3izRZjD2BbDDwnMh2i_17fI',
    appId: '1:994299555936:ios:13510feb6d59a58abc1305',
    messagingSenderId: '994299555936',
    projectId: 'chat-app-f3159',
    storageBucket: 'chat-app-f3159.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbgDC-7jRc3izRZjD2BbDDwnMh2i_17fI',
    appId: '1:994299555936:ios:13510feb6d59a58abc1305',
    messagingSenderId: '994299555936',
    projectId: 'chat-app-f3159',
    storageBucket: 'chat-app-f3159.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgdvMj2O-eBYOvbjxC7YosuMVfXYf6vaY',
    appId: '1:994299555936:web:30854c4a19fd6fc0bc1305',
    messagingSenderId: '994299555936',
    projectId: 'chat-app-f3159',
    authDomain: 'chat-app-f3159.firebaseapp.com',
    storageBucket: 'chat-app-f3159.appspot.com',
  );
}
